'use client';

import { useState, useEffect } from 'react';
import { useToast } from '@/hooks/use-toast';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import { api } from '@/lib/api';
import { useAuth } from '@/lib/authContext';
import { DollarSign, User } from 'lucide-react';

interface AddRevenueModalProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    onSuccess: () => void;
}

export function AddRevenueModal({
    open,
    onOpenChange,
    onSuccess,
}: AddRevenueModalProps) {
    const { toast } = useToast();
    const { user } = useAuth();
    const [members, setMembers] = useState<any[]>([]);
    const [formData, setFormData] = useState({
        member_id: '',
        amount: '',
        source: 'Referral',
        date: new Date().toISOString().split('T')[0],
        notes: '',
    });
    const [isLoading, setIsLoading] = useState(false);

    useEffect(() => {
        if (open && user?.token) {
            api.getUsers(user.token).then(setMembers).catch(console.error);
        }
    }, [open, user]);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setIsLoading(true);

        try {
            const payload = {
                member_id: parseInt(formData.member_id),
                amount: parseFloat(formData.amount),
                type: formData.source, // Backend expects 'type'
                date: new Date().toISOString().split('T')[0], // YYYY-MM-DD
                notes: formData.notes
            };

            await api.addRevenue(user?.token || '', payload);

            toast({
                title: 'Revenue Added',
                description: `Revenue of ₹${payload.amount} recorded successfully!`,
            });

            onOpenChange(false);
            onSuccess();

            // Reset form
            setFormData({
                member_id: '',
                amount: '',
                source: 'Referral',
                date: new Date().toISOString().split('T')[0],
                notes: '',
            });

        } catch (error) {
            console.error(error);
            toast({
                title: 'Error',
                description: 'Failed to add revenue',
                variant: 'destructive'
            });
        } finally {
            setIsLoading(false);
        }
    };

    const handleChange = (
        e: React.ChangeEvent<
            HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement
        >
    ) => {
        const { name, value } = e.target;
        setFormData(prev => ({
            ...prev,
            [name]: value,
        }));
    };

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="max-w-md glass-card border-white/20">
                <DialogHeader>
                    <DialogTitle className="gold-text">Record Revenue</DialogTitle>
                    <DialogDescription>
                        Add revenue generated by a member
                    </DialogDescription>
                </DialogHeader>

                <form onSubmit={handleSubmit} className="space-y-4">
                    {/* Member Selection */}
                    <div className="space-y-2">
                        <Label htmlFor="member_id" className="text-sm font-medium">
                            Member
                        </Label>
                        <div className="relative">
                            <User className="absolute left-3 top-3 w-4 h-4 text-muted-foreground" />
                            <select
                                id="member_id"
                                name="member_id"
                                value={formData.member_id}
                                onChange={handleChange}
                                className="glass-input w-full pl-10"
                                required
                            >
                                <option value="">Select a member</option>
                                {members.map(m => (
                                    <option key={m.id} value={m.id}>{m.name}</option>
                                ))}
                            </select>
                        </div>
                    </div>

                    {/* Amount */}
                    <div className="space-y-2">
                        <Label htmlFor="amount" className="text-sm font-medium">
                            Amount (₹)
                        </Label>
                        <div className="relative">
                            <DollarSign className="absolute left-3 top-3 w-4 h-4 text-muted-foreground" />
                            <Input
                                id="amount"
                                name="amount"
                                type="number"
                                placeholder="0.00"
                                value={formData.amount}
                                onChange={handleChange}
                                className="glass-input pl-10"
                                required
                            />
                        </div>
                    </div>

                    {/* Source */}
                    <div className="space-y-2">
                        <Label htmlFor="source" className="text-sm font-medium">
                            Source
                        </Label>
                        <select
                            id="source"
                            name="source"
                            value={formData.source}
                            onChange={handleChange}
                            className="glass-input w-full"
                        >
                            <option value="Referral">Referral</option>
                            <option value="Membership">Membership</option>
                            <option value="Event">Event</option>
                            <option value="Other">Other</option>
                        </select>
                    </div>

                    {/* Date */}
                    <div className="space-y-2">
                        <Label htmlFor="date" className="text-sm font-medium">
                            Date
                        </Label>
                        <Input
                            id="date"
                            name="date"
                            type="date"
                            value={formData.date}
                            onChange={handleChange}
                            className="glass-input"
                            required
                        />
                    </div>

                    {/* Notes */}
                    <div className="space-y-2">
                        <Label htmlFor="notes" className="text-sm font-medium">
                            Notes
                        </Label>
                        <Input
                            id="notes"
                            name="notes"
                            placeholder="Details about this revenue"
                            value={formData.notes}
                            onChange={handleChange}
                            className="glass-input"
                        />
                    </div>

                    {/* Submit Button */}
                    <Button
                        type="submit"
                        disabled={isLoading}
                        className="w-full bg-primary hover:bg-primary/90 text-primary-foreground font-semibold flex items-center justify-center gap-2 mt-4"
                    >
                        <DollarSign className="w-4 h-4" />
                        {isLoading ? 'Recording...' : 'Record Revenue'}
                    </Button>
                </form>
            </DialogContent>
        </Dialog>
    );
}
