"""Add organized_by

Revision ID: 5b449e6f09fc
Revises: 70010e2471b9
Create Date: 2026-02-20 14:56:30.296256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b449e6f09fc'
down_revision = '70010e2471b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organized_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_meeting_organized_by_user', 'user', ['organized_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_constraint('fk_meeting_organized_by_user', type_='foreignkey')
        batch_op.drop_column('organized_by')

    # ### end Alembic commands ###
