"""Add photo column

Revision ID: 70010e2471b9
Revises: a13344a8011b
Create Date: 2026-02-19 09:20:48.113834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70010e2471b9'
down_revision = 'a13344a8011b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
