"""backend refactoring upgrade

Revision ID: b78b33492c13
Revises: 5b449e6f09fc
Create Date: 2026-02-21 12:15:49.791534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78b33492c13'
down_revision = '5b449e6f09fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('one_to_one',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('with_member_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('topics_discussed', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['with_member_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.drop_column('heat')

    with op.batch_alter_table('revenue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appreciation_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('appreciation_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('services_offered', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('services_offered')
        batch_op.drop_column('business_name')

    with op.batch_alter_table('revenue', schema=None) as batch_op:
        batch_op.drop_column('appreciation_reason')
        batch_op.drop_column('appreciation_message')

    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heat', sa.VARCHAR(length=20), nullable=True))

    op.drop_table('one_to_one')
    # ### end Alembic commands ###
